### ISSUE TITLE
Memoizing geo masking by model_id and polygon not guaranteed to be unique

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/climate-explorer-backend#11]
Problem:
As per https://github.com/pacificclimate/climate-explorer-backend/pull/10#discussion_r49415916, while model_id is currently adequate to differentiate between model grids, this will break with other data.

Solution:
Modify `memoize_mask` to key on grid properties rather than model_id.

**Comment by jameshiebert** [comment]
Fixed in #71
