### ISSUE TITLE
Write user docs to explain the possible gaps in hypsometric curve

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-backend#112]
See https://github.com/pacificclimate/climate-explorer-backend/pull/108#discussion_r354479173

**Comment by rod-glover** [comment]
Doc is written, question is where it should be stored and how we plan to deliver it to MoTI, including "along with what else". Right now it's on my computer in Markdown + LaTeX.

**Comment by corviday** [comment]
Documentation was added to the [sphinx API documents](https://github.com/pacificclimate/climate-explorer-backend/blob/master/doc/source/api/watershed-api-usage.md). We may also want to put it elsewhere, but I am closing this issue for now.
