### ISSUE TITLE
Render `percentileanomaly` data items as lists rather than dicts

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-backend#133]
At present, `percentileanomaly` renders the data results (the anomaly and baseline data proper) as nested dicts, which are harder to filter than they need be. 

Instead of this:

```
{
  ...,
  "anomaly": {
    "yearly": {
      "2055-07-02 00:00:00": [ 2.3264379226208, 3.2458067672088 ]
    },
    "monthly": {
      "2055-01-15 00:00:00": [ 2.1310248585852, 3.3104322776824],
      "2055-02-15 00:00:00": [ 2.0116830378, 2.802655705519 ],
      "2055-03-15 00:00:00": [ 2.176002151962, 2.8835552547429 ],
      ...
    },
    "seasonal": {
      "2055-01-16 00:00:00": [ 2.7983318484797, 3.3868735586218 ],
      "2055-04-16 00:00:00": [ 2.3564425042040, 3.200660500285 ],
      "2055-07-16 00:00:00": [ 2.0237840492108, 3.1990939413123 ],
      ...
    }
  },
 ...
}
```
render this:

```
{

  ...,
  
  "anomaly": [
    // january; timeindex = 0
    {
      "timescale": "monthly",
      "date": "2055-01-15 00:00:00",
      "values": [ 2.1310248585852, 3.3104322776824]
    },
    
    ...,
    
    // winter; timeindex = 12
    {
      "timescale": "seasonal",
      "date": "2055-01-16 00:00:00",
      "values": [ 2.7983318484797, 3.3868735586218 ]
    },
    
    ...,
    
    // yearly; timeindex = 16
    {
      "timescale": "yearly",
      "date": "2055-07-02 00:00:00",
      "values": [ 2.3264379226208, 3.2458067672088 ]
    }
  ],
  
  ...

}
```

Notes:
1. Order matters: in order of "timeindex" as we call it in various places, i.e., jan, feb, mar, ..., winter, spring, summer, fall, yearly.
1. Key "timescale" in each data object is not strictly necessary but may be convenient. And would handle cases where various timescales were absent. For further contemplation.
1. No comments of course in the rendered JSON.

**Comment by jameshiebert** [comment]
@rod-glover This should be fairly simple to implement, but just to confirm: this would be a non-backward-compatible API change and require a major version increment?

**Comment by rod-glover** [comment]
Yes; only P2A is a client, and that code is recent, but this is a major version increment.
