### ISSUE TITLE
Provide units in /metadata and /multimeta responses

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-backend#142]
Presently these endpoints return only the variable name, and not its units. 

This is a real problem for Plan2Adapt, for which this is by far the most robust solution.

PCEX might reasonably be expected to display and use units of climate layers datasets, but it does not because at this point it cannot. (The endpoint `/data` _does_ supply units and indeed they are displayed for data from this endpoint.)

The `/metadata` and `/multimeta` endpoints return metadata in the following format (example of tasmax dataset):

```
tasmax_aClim_BCCAQv2_bcc-csm1-1-m_historical-rcp45_r1i1p1_19610101-19901231_Canada: {
  end_date: "1990-12-31T23:59:59Z"
  ensemble_member: "r1i1p1"
  experiment: "historical,rcp45"
  institution: "PCIC"
  model_id: "bcc-csm1-1-m"
  model_name: null
  modtime: "2017-09-22T00:37:58Z"
  multi_year_mean: true
  start_date: "1961-01-01T00:00:00Z"
  timescale: "yearly"
  variables: {
    tasmax: "Daily Maximum Near-Surface Air Temperature"
  }
}
```

We should add units as follows:

```
tasmax_aClim_BCCAQv2_bcc-csm1-1-m_historical-rcp45_r1i1p1_19610101-19901231_Canada: {
  ...,
  variables: {
    tasmax: "Daily Maximum Near-Surface Air Temperature"
  },
  units: {
    tasmax: "degC"
  }
}
```

**Comment by cairosanders** [comment]
How can I test my changes? (Manually or automatically)
