### ISSUE TITLE
Black as a Git pre-commit hook

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-backend#158]
The differences between what I can make my IDE enforce and what Black demands is driving me up the wall. There is a solution, and it's one we've discussed before. It's called a pre-commit hook, which is (roughly) a script that runs before every commit. It's now easier than ever:

- Package [pre-commit](https://pre-commit.com/) makes installing pre-commit hooks very easy.
- [This blog post](https://www.mattlayman.com/blog/2018/python-code-black/) describes how to set up Black as a pre-commit hook. (Search for "Black as a Git pre-commit hook", well down the page.)

I'd be happy to give this a go. If/when we decide we like it, we can transfer it to other Python repos. @nikola-rados , do you have any comment?

**Comment by rod-glover** [comment]
This issue supersedes #157 .

**Comment by nikola-rados** [comment]
I've never heard of these but I would certainly be happy to try them out. I read the resources you posted an it seems easy enough to get things up and running.
