### ISSUE TITLE
Grid test is too verbose

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/climate-explorer-backend#16]
[This commit](https://github.com/pacificclimate/climate-explorer-backend/commit/19621a4916423980d272e1cf2c8124eb99fae352) added [a test]() that precisely checks the values of test input.

This is too verbose and would need to be rewritten any time the test input data changes. Please loosen the assertions here. Other alternatives, for example, could be:

* Just check that the keys "latitudes" and "longitudes" exist in the dict
* Just check that the length of the lists is > 0
* Just check that some of the values in the list are > 0

Essentially, the application should be guaranteed to work with any input data, so having the test assertions too closely coupled with the test input data makes the tests annoying to read and difficult to maintain over time.

**Comment by mdfischer** [comment]
Fixed.
