### ISSUE TITLE
Add relief ratio to watershed API

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#172]
MOTI has requested the [relief ratio](https://en.wikipedia.org/wiki/Relief_ratio) be added to the `watershed` API. This is the difference between the elevation of the source of a stream and its mouth divided by the length of the stream, but it's not entirely clear what "Source" means. Arelia will consult with Markus and get back to use on what the exact algorithm should be. 

The `watershed` API has all the relevant data (elevation, flow direction map) already, we just need to figure out the algorithm.

**Comment by corviday** [comment]
Directions from @AreliaTW on how to calculate the Melton ratio:

> 1) Find the highest and lowest cells in the watershed area
> 2) Subtract the lowest elevation from the highest to get watershed relief
> 3) Divide this by the square root of the watershed area

Should be straightforward.

**Comment by corviday** [comment]
What are the units?

**Comment by corviday** [comment]
We've decided the units of a ratio should be "1", the SI standard.

**Comment by AreliaTW** [comment]
To compute the Melton ratio “watershed relief divided by the square root of watershed area” (Melton 1957), where “the relief ratio is a number calculated to describe the grade of a river or stream. The calculation is just the difference in elevation between the river's source and the river's confluence or mouth divided by the total length of the river or stream. This gives the average drop in elevation per unit length of river.”

Relief units = m - m / m = m/m = unitless
Melton ratio = unitless/sqrt(km2)

Units overall = 1/km2 or km-2

**Comment by AreliaTW** [comment]
I think they units for the relief is 1 and the units for the Melton Ratio is 1/km2. I am confirming with Markus.

**Comment by AreliaTW** [comment]
I had been using the relief ratio (km/km) when I should have been using the relief (km) in the previous posts so I deleted them.

I look it up in this document.
https://www.for.gov.bc.ca/hfd/library/fia/2004/FSP_R04-020c.pdf

What I saw was:
Melton ratio: Watershed relief (km) divided by the square root of watershed area (km). (Melton1957; Patton and Baker1976; Jackson et al.1987) units km/km

So you can report it as km/km or "1" if you prefer the SI standard.

Thank you.

**Comment by rod-glover** [comment]
My 2 cents: If "km/km" is more expressive, I'd use it.

**Comment by corviday** [comment]
Is "km/km" better than "m/m"? Our elevation and area data is in meters, but it's not exactly a difficult conversion. :)
