### ISSUE TITLE
Allow selection of percentile cell_methods data

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#175]
Hydrology has made some datasets containing percentile results across an ensemble of 50 datasets. They want us to use these datasets to display a "confidence interval" on a graph, but we don't want people to be able to select them as first order data. 

This is similar to the situation with the standard deviation datasets, which are used by plan2adapt's rules engine, but are not displayed in PCEX as first order datasets.

Currently, the backend's method for handling the standard deviation data looks like this:
* search the `cell_methods` variable attribute for the string `standard_deviation`
* if the string is present, this is a climatological standard deviation dataset, to be returned to the user only if explicitly asked for
* if the string is not present, this is a climatological mean dataset, displayed by default

This approach is a little clumsy because `cell_methods` strings are [noisy and unreliable](https://github.com/pacificclimate/climate-explorer-data-prep/issues/64).

We want to do something similar with the new percentile-of-model-ensemble datasets. Instead of bolting on more regexes, we want to incorporate the [cell_methods parser](https://github.com/pacificclimate/cf-cell-methods) to determine whether a given cell method is a standard deviation over climatology, a pecentile over model ensemble, or other, assumed climatological mean. This will give us a good base to work from for more complicated cell methods manipulations when the method strings have been cleaned up.

**Comment by rod-glover** [comment]
What pattern of cell methods are we looking at for these cases? Let me hazard a guess or two:
- standard deviation over climatology: 
  - `<CF climatology case> <axis?>: standard_deviation`
  - Over what axis is the standard deviation taken?
- percentile over model ensemble
  - `<any cell methods> model: percentile[n]`, where `n` is a number
  - Is there any need to match/validate on the `<any cell methods>` or is that really an accurate statement (no constraints)?

I think both of these cases are fairly easily handled with existing tools in the cf-cell-methods semantics module. They will look like some of the examples there. 

Question: Do you think these specialized matching functions belong in the cf-cell-methods package? That means we have to release a new version when we want to do things like this issue requires. Maybe better to just abstract a few common operations there and put the more specialized tests inside the client package (i.e., this one)?

**Comment by corviday** [comment]
Standard deviation cell methods (taken from the database):
* `time: mean time: standard_deviation over days` (pr)
* `time: maximum time: standard_deviation over days` (tasmax)
* `time: minimum time: standard_deviation over days` (tasmin)

I think they're basically climatological means, but mean are replaced with standard deviations. They're made by the usual `generate_climos` script.

At this point there is not need to parse the <any cell methods> component of the percentiles over model ensemble. It seems like once we're set up with the parser, we can add that later if we ever need it for some reason.

**Comment by rod-glover** [comment]
OK. Parser is ready to go. I've added a couple of refinements since release 0.1.0, but they are minor. You can, if you choose, use it to match any of these. The code pattern for the "hydrology" cell methods in the semantics module is easily used to cover these too.

**Comment by corviday** [comment]
Thanks!
