### ISSUE TITLE
New release slower than previous release

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#178]
The most recent release of the backend, 3.3.0 seems to have slowed down the data query.

Old data query: 25.941 seconds
New data query: 32.370 seconds

The multistats query, also affected in this release, seems to have also slowed down a little.

Old multistats query: 4.798 seconds
New multistats query: 5.432 seconds

**Comment by corviday** [comment]
After more rigorous testing with dockers on docker-dev01, I am not seeing this effect.

**Comment by corviday** [comment]
Actually, the production server is running version 3.1.0. The backend _has_ gotten slower, but it was between 3.1.0 and 3.2.0, not 3.2.0 and 3.3.0. So I didn't see it testing with one 3.2.0 and one 3.3.0 docker.

**Comment by corviday** [comment]
Unexpectedly, it looks like the "extra" time in the data API all comes from the `get_units_from_run_object()`, possibly introduced when we [rewrote it to only check the units of the selected ensemble](https://github.com/pacificclimate/climate-explorer-backend/pull/169). 

Profile of 3.1.0:
![310profile](https://user-images.githubusercontent.com/4512605/107456797-bb850e80-6b05-11eb-8a65-8393070a9bc7.png)

Profile of 3.2.0
![320profile](https://user-images.githubusercontent.com/4512605/107456798-bc1da500-6b05-11eb-9259-15073e65f3ec.png)

Profile of 3.3.0
![330profile](https://user-images.githubusercontent.com/4512605/107456799-bc1da500-6b05-11eb-91b8-26d47c7a052a.png)

**Comment by jameshiebert** [comment]
Taking a look at the code for [`get_units_from_file_object()`](https://github.com/pacificclimate/climate-explorer-backend/blame/67d41379e58691e49271da0adf9d48b546acc151/ce/api/util.py#L33) I see one main potential problem.

The function in question does an object traversal on an ORM object within a `for` loop. In effect, this ends up reaching out to the database (a relatively slow operation), for each iteration of the loop. A much faster way to accomplish this would be to query all of the relevant attributes in a single go.

Not sure of the SQLAlchemy/ORM analogue, but for [getting the units](https://github.com/pacificclimate/climate-explorer-backend/blame/67d41379e58691e49271da0adf9d48b546acc151/ce/api/util.py#L42) this would be something like: `SELECT DISTINCT units FROM variable_alias...`. Essentially, you can easily do this with a single database query in SQL and one should be able to do the same with SQLAlchemy. I would *expect* that this would speed it back up to the response times that we were seeing before.

**Comment by rod-glover** [comment]
I agree. Traversing a database like that with SQLAlchemy is convenient but frequently very slow. I did add a comment to this effect on an earlier PR on this code.
