### ISSUE TITLE
add an API endpoint that returns the downstream path from a selected point

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#197]
Currently the "watershed" API [returns a geoJSON `Polygon` representing the boundary of all grid squares upstream from a selected point](https://services.pacificclimate.org/pcex/api/streamflow/watershed?ensemble_name=upper_fraser_watershed&station=POINT+(-121.484375+53.645834)). This polygon can be  used by the front end to display the selected watershed on a map, or to query a different API about climate data within a watershed.

We would like a new API that returns a geoJSON LineString representing the path downstream from a selected point to the sea, or to the edge of the flow map. The edge of the map or the mouth of a river into the sea will have a value of "0" in the flow map netCDF file.  This will be useful to the BC-SRIF project for showing the route the salmon take to get to the sea.

The new API should accept a `Point` in WKT format, and the name of the ensemble containing the flow map.

This downstream path will be displayed on the portal map, similar to this mockup:

![gridmmap](https://user-images.githubusercontent.com/4512605/151857547-5ce93593-e401-4055-850c-f0b1df17b5ec.png)

**Comment by jameshiebert** [comment]
Some proposed steps for approaching this problem:

1. Find the example flow network data (in the tests).
    1. Use NetCDF binary tools on the command line to visualize and dump its output to the terminal
    2. Use the [Python NetCDF](https://github.com/Unidata/netcdf4-python) library to access the flow network file.. Review the first half of [this tutorial](https://unidata.github.io/netcdf4-python/), focusing on ways to *read* the data.
2. Find the watershed API code, particularly the code that computes all cells in the upstream *area*.
3. Parametrize the upstream area function(s) to use a different search criterion (downstream vs. up)
4. The upstream area function converts a set of cells into a polygon (the result of a union of [boxes](https://shapely.readthedocs.io/en/stable/manual.html#shapely.geometry.box). Convert your cells into a [linestring](https://shapely.readthedocs.io/en/stable/manual.html#linestrings) instead.
5. Add your new API function to [the list of methods available](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/__init__.py#L29)
6. Write some automated tests for your new API function.
