### ISSUE TITLE
Speed up watershed API for large watersheds

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#211]
Previously, we only ran the `watershed` API against the Upper Fraser, but now we are running it over the entire Fraser, and it times out sometimes when covering large areas. Profile the API and look for ways to speed it up.

Possibilities to look into:
* upgrade python version in the backend
* make optional (if parameter supplied) some of the debug outputs we have now
* split the API into multiple APIs, one of which _only_ calculates the watershed area, the other of which calculates the Melton Ratio statistics, given a watershed
* use smaller elevation and area files; I think they're both the entire Northwest
* the frontend calls this API twice for each selection - once to draw the drainage area on the map, and a second time to calculate the Melton Ratio. Could the problem just be this double-tap, and if the frontend saved the data and hit half as often, it would be an improvement?

**Comment by corviday** [comment]
Here are the initial profiling results. 

![profile1](https://user-images.githubusercontent.com/4512605/167721937-f374906e-277d-420a-b938-72080be522f4.png)

It spends a surprising amount of time in `get_values_at_lonlats()` and `lonlat_to_xy()`, but these are fairly straightforward functions and it's not obvious how to improve their performance. Caching?

**Comment by corviday** [comment]
Additional thoughts:
<hr>
Some of the things this API returns are complex and have to be calculated with purpose-written code, such as the flow network and the hypsometric graph. 

But the total area, elevation maximum, and elevation minimum are much simple calculations. Instead of extracting individual grid squares from the relevant files and doing calculations with them, I think we could just use built-in faster access and calculation functions in `rasterio` and `numpy`. It will make the code a little longer - we won't be using the same set of code to access each file any more, but I think it would speed things up at least a bit. Worth a test, anyway.
<hr>
@jameshiebert suggested looking into `asyncio` for faster file IO.
<hr>

**Comment by corviday** [comment]
I switched the elevation minimum and elevation maximum calculations to use `get_array()`, similarly to the way the `stats` API works, instead of the custom calculations done with `VicDataGrid`. This speeds up the runtime of the entire Fraser from 29 seconds to 20 seconds on my workstation.

Those were the "easy" calculations - a file is accessed and a minimum or maximum calculated. It is probably possible to switch the more complex hypsometric graph calculations to use `get_array'()` as well, perhaps for another 30% speedup, but it will require uglier code.

Tests will also need to be updated.

**Comment by corviday** [comment]
Updated `cascaded_union()` to `unary_union()` as suggested by shapely. No speed improvement.

**Comment by corviday** [comment]
Here's the profile from this branch, which preloads all the array data into numpy (RAM) instead of hitting the file each time it wants to access a grid cell. It's about twice as fast as the unmodified version, but it needs to be faster yet, so we are looking for additional improvements.
![preload-arrays](https://user-images.githubusercontent.com/4512605/176262560-32a61e03-c40a-4cb3-bc39-f4bc8d091fc2.png)

**Comment by corviday** [comment]
Surprisingly, the amount of RAM available to the container doesn't seem to affect calculation speed much. 

| Container RAM | Execution Speed |
|---------------|-----------------|
| 5G            | 37.67           |
| 7G            | 37.38           |
| 9G            | 37.86           |

**Comment by rod-glover** [comment]
> Here's the profile from [this branch](https://github.com/pacificclimate/climate-explorer-backend/tree/preload-watershed), which preloads all the array data into numpy (RAM)

@corviday , I looked at that branch and I noticed that the following things that could still be slowing things down:
1. Long and lat are not preloaded. Try `dataset.variables["lon"][:]`, ditto lat.
2. The 2D variable may only be partially preloaded. It has this: `dataset.variables[variable_name][:]` but may need this `dataset.variables[variable_name][:,:]` since there are two axes (indexes) on those.

**Comment by corviday** [comment]
Thanks, I'll check those out.

**Comment by corviday** [comment]
Oh wow, initial tests suggest preloading lat and lon matrix data speeds things up by 4x!

**Comment by rod-glover** [comment]
That's great! Did you also try preloading the 2D variable matrix too, with `[:,:]`? Note two colons separated by comma. The one colon presently there might only preload some row info or something.

**Comment by corviday** [comment]
> That's great! Did you also try preloading the 2D variable matrix too, with `[:,:]`? Note two colons separated by comma. The one colon presently there might only preload some row info or something.

Yes; there is no noticeable difference.
