### ISSUE TITLE
sqlalchemy error

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#233]
Docker instances of the newest version (3.6.2) throw the following error when any API call is made:

```
2024-02-20 17:03:47 [13] [ERROR] Exception on /api/multimeta [GET]
Traceback (most recent call last):
File "/root/.cache/pypoetry/virtualenvs/ce-9TtSrW0h-py3.8/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1020, in __call__
return self.registry[key]
KeyError: 140433640835912
```

This does not seem to be an issue with our python code, as a version with identical code has been deployed as an unmerged branch. It is perhaps caused by an update to sqlalchemy.

**Comment by corviday** [comment]
The version of sqlalchemy used by the app has not changed.

The error does not occur outside of docker

The file referenced in the error does exist

**Comment by corviday** [comment]
I built a docker from `32ce883`, and it did not have the error, so I think the error was introduced sometime after that hash, though it is still unclear what sort of error might appear only in docker containers and not on bare metal.

**Comment by jameshiebert** [comment]
@corviday have you tried running the test suite in a docker container? Does the `/multimeta` API call fail under that environment? Just trying to get a minimal test case so that we can narrow this down and work on it.

**Comment by corviday** [comment]
That's a great idea, thanks. The test suite has some failures, but they seem to be unrelated (a needed directory isn't mounted to the container) but other tests pass. I don't know what that means, but it's useful.

**Comment by jameshiebert** [comment]
OK, that being the case can you give a full "steps to reproduce" overview then?

**Comment by corviday** [comment]
Steps to reproduce:

1. Build a docker of release version 3.6.2, or use the one on docker hub
2. Start the docker
3. access any API endpoint that uses the database to get an error. /multimeta is an easy one because it has defaults for all the parameters.

Given that tests work, issue is likely flask-related.

**Comment by jameshiebert** [comment]
Can you be more specific about what parameters you're using for step 2 and exactly what URL you're using from step 3? I still cannot reproduce this.

**Comment by corviday** [comment]
That's good news, I think?

Here are the current docker-compose.yaml and be.env files, with their extension changed and passwords redacted.
[be.env.txt](https://github.com/pacificclimate/climate-explorer-backend/files/14390881/be.env.txt)
[docker-compose.yaml.txt](https://github.com/pacificclimate/climate-explorer-backend/files/14390882/docker-compose.yaml.txt)

Here is my [test URL](http://docker-dev02.pcic.uvic.ca:30070/api/multimeta?ensemble_name=ce_files&extras=filepath).

**Comment by corviday** [comment]
Things that don't fix it:

* downgrading flash packages to previous versions
* switching database connection string to previous version

Switching GDAL and / or python back has so far proved to be quite a tangle

**Comment by corviday** [comment]
Reopened an old branch that previously worked, but that one now has an error too.

**Comment by corviday** [comment]
Released a new version (3.6.3), which works in github tests, but not in docker containers.

I now have an instance of 3.6.3 running on my workstation and running on docker-dev02. They have identical libraries according to pip freeze.

My desktop is using python 3.8.10 and docker-dev02 is using 3.8.15. That seems unlikely to be the problem, but I don't have any better ideas, so maybe I will try changing that next.

**Comment by corviday** [comment]
> Another possibility is something specific to gunicorn.

Running it on my workstation as `poetry run gunicorn --config docker/gunicorn.conf ce.wsgi:app` results in no errors. 

**Current investigative Summary:**
So this runs on my workstation and on github but not on docker-dev02.; the difference is not:
* any python packages - identical versions are present on working and non-working instances
* usage / non usage of github
* any code difference in our code
* different version of poetry

Next things to check: python versions, postgres C library versions. running in a docker container

**Comment by corviday** [comment]
I updated a bunch of things in the `geospatial-python` container to address a different error, and it appears to have fixed this issue as well.
