### ISSUE TITLE
numpy build error

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#243]
The poetry build on github has stopped working. This is a new-ish error, first cropping up last week.

Build errors that seem relevant:

> Failed to install setuptools>=41.2, numpy>=1.26.0b1; python_version>='3.12.0.rc1', oldest-supported-numpy; python_version<'3.12.0.rc1', wheel, cython>=0.29.20.

>  Note: This error originates from the build backend, and is likely not a problem with poetry but with numpy (1.17.3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "numpy (==1.17.3)"'.

> Cannot install build-system.requires for cftime.

`numpy 1.17.3` is import by `oldest-supported-numpy`
`oldest-supported-numpy` is imported by `cftime`
`cftime` is imported by `netcdf4`
`netcdf4` is imported by `nchelpers`
`nchelpers` is imported by `climate-explorer-backend`. 

poetry can't install `numpy 1.17.3`.

Questions:
1. How can this be fixed?
2. Why did it break Friday September 6th. when it was previously working? What changed? Is there a package we can pin to an old version to get it to work again, or did some sort of cache expire in a way we can't easily turn back the clock on?

**Comment by corviday** [comment]
Things that haven't worked:

* pinning netcdf4 to 1.5*, 1.6*, or 1.7*
* explicitly pinning cftime
* explicitly pinning numpy

Things that have worked but that we don't want to do:
* downgrading from poetry to pip

**Comment by corviday** [comment]
Weirdly, `poetry show --tree` doesn't show this issue at all:

```
climate-explorer-backend$ poetry show --tree | grep numpy
│   │   │   └── numpy >1.13.3 
│   │   └── numpy * (circular dependency aborted here)
│   │   └── numpy >1.13.3 
│   └── numpy * (circular dependency aborted here)
├── numpy *
│   │   └── numpy >1.13.3 
│   └── numpy * (circular dependency aborted here)
numpy 1.24.4 Fundamental package for array computing in Python
├── numpy *
    ├── numpy * 
└── numpy >=1.14
```

No mention of `oldest-supported-numpy`.

**Comment by jameshiebert** [comment]
Can you add the output of `poetry env info`? Wondering what version of Python you're using.

**Comment by corviday** [comment]
```
RUN poetry env info

Virtualenv
Python:         3.8.15
Implementation: CPython
Path:           NA
Executable:     NA

Base
Platform:   linux
OS:         posix
Python:     3.8.15
Path:       /usr
Executable: /usr/bin/python3.8
```

**Comment by corviday** [comment]
`cftime` started using oldest-supported-numpy with [this commit](https://github.com/Unidata/cftime/commit/b3428ec4b2dfed00101cc2a8216262a826999cfd) in June of this year. Unfortunately, [netCDF4 doesn't import any particular version of `cftime`,](https://github.com/Unidata/netcdf4-python/blob/master/pyproject.toml) so I don't think we can just downgrade `netCDF4` to get the older version of `cftime`. 

Perhaps we can try importing a particular version of `cftime` in `nchelpers`?

**Comment by jameshiebert** [comment]
> ```
> RUN poetry env info
> 
> Virtualenv
> Python:         3.8.15
> Implementation: CPython
> Path:           NA
> Executable:     NA
> 
> Base
> Platform:   linux
> OS:         posix
> Python:     3.8.15
> Path:       /usr
> Executable: /usr/bin/python3.8
> ```

3.8 is [only in security status for another few days-to-weeks](https://devguide.python.org/versions/). We really shouldn't be hanging our hats on it. Can you at least shoot for 3.9 or 3.10?

**Comment by corviday** [comment]
I tried updating to python 3.9, but it is still trying and failing to install `oldest-supported-numpy`, which is weird. Here's what `cftime`'s `pyproject.toml` says:

```
[build-system]
requires = [
    "setuptools>=41.2",
    "cython>=0.29.20",
    "wheel",
    "oldest-supported-numpy ; python_version < '3.9'",
    "numpy>=2.0.0rc1,<3 ; python_version >= '3.9'",
]
build-backend = "setuptools.build_meta"
```

So it seems like python 3.9 should _not_ try to install `oldest-supported-numpy`.

I also tried updating to python 3.10, but hit a different error I'm still working on.

**Comment by corviday** [comment]
Deployed the `geospatial-python` container to docker swarm and began install libraries one at a time by hand. This resulted in much more detailed error messages, one of which explicitly said that python > 3.9 and < 3.15 was needed. I am not sure why this is different than the the cftime pyproject,toml, which says python 3.9 should be sufficient. 

So I created an experimental version of the `geospatial-python` container that uses python 3.10, ubuntu 22.04, and gdal 3.4. That seems to have solved this particular problem, after updating code in this repository to python 3.10 as well.
