### ISSUE TITLE
Some polygons return all 0's in timeseries call

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/climate-explorer-backend#26]
Some calls to the `timeseries` backend return all zeros. [This](http://docker1.pcic.uvic.ca:20003/api/timeseries?id_=prcptotETCCDI_yr_BCCAQ-ANUSPLIN300-CanESM2_historical-rcp26_r1i1p1_1950-2100&variable=prcptotETCCDI&area=
POLYGON+%28%28-123+48,+-123+49.80,+-122+49.80,+-122+48,+-123+48%29%29) works as expected.
`area=
POLYGON+((-123+48,+-123+49.80,+-122+49.80,+-122+48,+-123+48))`

But [this one](http://docker1.pcic.uvic.ca:20003/api/timeseries?id_=prcptotETCCDI_yr_BCCAQ-ANUSPLIN300-CanESM2_historical-rcp26_r1i1p1_1950-2100&variable=prcptotETCCDI&area=
POLYGON+%28%28-123+49.8,+-123+49.9,+-122+49.9,+-122+49.8,+-123+49.8%29%29) returns all zeros.
`area=
POLYGON+((-123+49.8,+-123+49.9,+-122+49.9,+-122+49.8,+-123+49.8))`

Appears to have to do with how low the northern extent of a polygon is, not size/orientation.

**Comment by jameshiebert** [comment]
May be related to #53

**Comment by jameshiebert** [comment]
Pretty sure that #55 addressed this:

```bash
$ curl -s "http://docker2.pcic.uvic.ca:8888/api/timeseries?id_=tasmin_mClim_BCCAQv2_bcc-csm1-1-m_historical-rcp45_r1i1p1_19610101-19901231_Canada&variable=tasmin&area=POLYGON+((-123+49.8,+-123+49.9,+-122+49.9,+-122+49.8,+-123+49.8))" | python -m json.tool
{
    "data": {
        "1977-01-15T00:00:00Z": -8.800346342307693,
        "1977-02-15T00:00:00Z": -7.255077124615385,
        "1977-03-15T00:00:00Z": -6.238004753076924,
        "1977-04-15T00:00:00Z": -3.1872571467692308,
        "1977-05-15T00:00:00Z": 0.6159948996923078,
        "1977-06-15T00:00:00Z": 3.77390777723077,
        "1977-07-15T00:00:00Z": 6.391181838461539,
        "1977-08-15T00:00:00Z": 7.024783299692308,
        "1977-09-15T00:00:00Z": 3.6264821686153845,
        "1977-10-15T00:00:00Z": 0.15834167676923075,
        "1977-11-15T00:00:00Z": -4.411500059076923,
        "1977-12-15T00:00:00Z": -7.6910155883076925
    },
    "id": "tasmin_mClim_BCCAQv2_bcc-csm1-1-m_historical-rcp45_r1i1p1_19610101-19901231_Canada",
    "units": "degC"
}
```
