### ISSUE TITLE
generate_climo scales precip units incorrectly for packed files 

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-backend#36]
`generate_climo` can (under control of a flag) convert precipitation units from per-second to per-day. Currently this conversion is done by multiplying by a scale factor of 86400 (s/day). This is correct for absolute (unpacked) files, but fails for packed files where the offset value is non-zero.

Solution is to recognize packed files and apply a different computation to them taking into account the scale and offset values.

Question: Is there a standard for how packed files are defined that we can adhere to, or is it ad hoc?

**Comment by jameshiebert** [comment]
> Question: Is there a standard for how packed files are defined that we can adhere to, or is it ad hoc?

I wrote a [blog post](http://james.hiebert.name/blog/work/2015/04/18/NetCDF-Scale-Factors/) a couple of years ago about the packing. It contains more information than you need, but it addresses some of the historic reasons for the ad-hoc nature of it, and also has a link to Unidata's best practices for packing.

But essentially, you should assume that it's ad-hoc and your code should take care.

**Comment by rod-glover** [comment]
Happily, [Unidata's best practices for packing](http://www.unidata.ucar.edu/software/netcdf/docs/BestPractices.html) do indicate standard names for the packing param attributes: `scale_factor` and `add_offset`. Those are in use in files Stephen Sobie is preparing. 

I'll treat this (plus integer data type for the variable) as the indicator for packed values; any other case will get treated as not packed, correctly or no. Possibly could raise an error if the variable data type is an integer but the expected attributes are not present, although this could conceivably be incorrect in some places.

**Comment by rod-glover** [comment]
Another question here is whether it is worth putting this effort in at the moment. It is only needed when precip needs to be scaled to different units, and Stephen says that his will always be in the desired units. I don't like leaving holes like that, but if we never use it, it might not be worth the effort to fix. As a placeholder, I could raise an exception when this condition is detected.

**Comment by rod-glover** [comment]
However, the procedure for units conversion (multiplication by a constant factor) is actually **simpler** in the case of packed values: To multiply the unpacked values by a constant value `K`, multiply both the scale factor and offset by `K`. The packed values do not change.

**Comment by jameshiebert** [comment]
> Stephen says that his will always be in the desired units

Well... many, many of the files that this software will service will not have been created personally by Stephen. We definitely need to cover this case.

> I'll treat this (plus integer data type for the variable) as the indicator for packed values

No, don't assume that it's packed based on an integer type. There are lots of use cases for an integer value that have nothing to do with packing. The presence of `add_offset` and/or `scale_factor` are the only indication of packing.

**Comment by rod-glover** [comment]
Yes, checking for integer is redundant to checking for packing parameters.

You say `add_offset` **and/or** `scale_factor`; so if one is present and the other missing, I will use the values 0 and 1 respectively for the missing parameter.

**Comment by jameshiebert** [comment]
Yep, that's perfect.

**Comment by rod-glover** [comment]
Fixed
