### ISSUE TITLE
Multimeta API call should expose time bounds

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#59]
The single-file [metadata API call](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/metadata.py) now includes `start_date`, `end_date`, and `multi_year_mean` metadata about each dataset, as requested in #44 . It would be convenient if the multi-file [multimeta API call](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/multimeta.py) exposed them too, but I'm open to discussion about the necessity of this.

At present, the climate explorer frontend [calls `multimeta` once on loading (line 17)](https://github.com/pacificclimate/climate-explorer-frontend/blob/master/src/components/AppMixin/AppMixin.js) to get information on all available datasets, which it uses to populate selectors and user-facing widgets with what datasets are available for examination. 

In order to be able to show the user what each dataset's climatological period is, either `multimeta` could provide that information, or climate-explorer-frontend could hit the single-file `metadata` call once for each file in the user-selected current group (ie, filtered by model, variable, and sometimes experiment). I think having `multimeta` provide the information up front would be a little nicer.

**Comment by jameshiebert** [comment]
I'd agree; responses from `metadata` and `multimeta` should be consistent.
