### ISSUE TITLE
multistat API call doesn't handle split climatology files

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#61]
Currently the [multistat API call](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/multistats.py) accepts an integer `timeidx` parameter, along with a set of filtering parameters: `ensemble`, `model`, `emission`, and `variable`. 

It returns a set of statistics calculated from the `timeidx`-th slice of each file that fit the rest of the parameters. 

It would be nice if it was possible to filter on `timescale` (monthly, seasonal, yearly) in addition to `ensemble`, `model`, `emission`, and `variable`, so that, for example, you could pass `timescale=monthly&timeidx=0` to get only statistical calculation corresponding to January, or `timescale=yearly&index=0` to get annual statistics.

It's completely possible to sort out which `timeidx=0` results are Januaries, which are winters, and which are annual in the front end, but I think it would make more sense to have the API do that filtering. It would more closely match [the revised functioning of the data query](https://github.com/pacificclimate/climate-explorer-backend/pull/60), and be more intuitive to a hypothetical new programmer, I imagine.

**Comment by jameshiebert** [comment]
Yeah, good observation. I'd agree that this is a good idea.
