### ISSUE TITLE
Area query on climdex file causes server crash

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#70]
[Timeseries query](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/timeseries.py) and [multistats query](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/multistats.py) crash the entire backend when made against a climdex file with an area specified.

**Comment by corviday** [comment]
My first suspicion was that this was another manifestation of [this data prep issue](https://github.com/pacificclimate/climate-explorer-data-prep/issues/11), but the crash occurs with files that have monotonic longitudes as well.

**Comment by corviday** [comment]
The crash occurs inside wrappered GDAL routines called with what appear to be entirely valid arguments. I poked around with GDB , but wasn't able to sort out anything useful or solve the issue from the GDAL end.

Instead I upgraded rasterio to the bleeding edge alpha version, because I know rasterio changed some of how transforms work with GDAL in the newest versions and I thought it might be different enough to avoid whatever mysterious thing was causing GDAL to crash. That seems to have fixed the issue. Need to do a little more testing before I'm sanguine about switching to the alpha version of such an essential library.

**Comment by jameshiebert** [comment]
OK, I'm in the process of upgrading our [geospatial-python docker image](https://hub.docker.com/r/pcic/geospatial-python/builds/) to use GDAL==2.2. Do you suspect that using that will help?

**Comment by corviday** [comment]
Seems like it would probably help.

**Comment by jameshiebert** [comment]
Example request that fails:

http://docker-dev01.pcic.uvic.ca:30123/api/timeseries?id_=altwsdiETCCDI_yr_BCCAQ_CNRM-CM5_historical-rcp85_r1i1p1_19500702-21000702&variable=altwsdiETCCDI&area=POLYGON+((-133.8134765625+51.14501953125,+-133.8134765625+54.90478515625,+-130.0048828125+54.90478515625,+-130.0048828125+51.14501953125,+-133.8134765625+51.14501953125))

or:

http://[host]:[port]/api/timeseries?id_=altwsdiETCCDI_yr_BCCAQ_CNRM-CM5_historical-rcp85_r1i1p1_19500702-21000702&variable=altwsdiETCCDI&area=POLYGON+((-133.8134765625+51.14501953125,+-133.8134765625+54.90478515625,+-130.0048828125+54.90478515625,+-130.0048828125+51.14501953125,+-133.8134765625+51.14501953125))

**Comment by corviday** [comment]
[This branch](https://github.com/pacificclimate/climate-explorer-backend/tree/bugfix/70) functions correctly and fixes this bug (as well as a bug that was preventing caching of masked data) on my workstation, but  crashes in a docker container. Running in a docker container, it can be reliably crashed by loading the frontend (therefore executing a `multimeta` query, a `metadata` query, a `timeseries` query, and a `stats` query) twice. Executing the same queries in a shell script with `curl` does not trigger a crash.

Possible causes to investigate:
- [ ] I'm not allocating the docker containers enough memory for the increased cache size
- [ ] There's a memory leak that takes much longer to be an issue on my workstation than in a container, so I'm just not seeing it on the workstation, but the problem is still there
-  [ ] Loading specific files triggers the crash, perhaps very large ones
 - [ ] Crash is related to the specific version of gdal or other prerequisites used in the docker container; different versions than are installed on my workstation

**Comment by jameshiebert** [comment]
So, I have run this branch on a compute node (``lynx.compute.pcic``) w/o Docker (simply running the ``devserver.py`` script) and cannot reproduce the crash. Everything seems to work fine. The process is only taking up a little over 1 MB of RAM, so I doubt that it's memory related:

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
9910 hiebert   20   0 1651068 976012  26596 S   4.3  1.9   3:03.19 python3.4
```

**Comment by jameshiebert** [comment]
So I have a Docker container running with 10 gunicorn workers that works without crashing the Docker container. It has taken the bugfixes in bugfix/70 and adds in Dockerfile that uses gunicorn instead of the . The work is in [this branch](https://github.com/pacificclimate/climate-explorer-backend/tree/feature/docker-prod) and is running [here](http://docker-dev01.pcic.uvic.ca:30123/api).

```bash
$ docker run -d -e GUNICORN_WORKERS=10 -e GUNICORN_CAPTURE_OUTPUT=True -e MDDB_DSN='postgresql://ce_meta_ro:{Mj2=4$n@db3.pcic.uvic.ca/ce_meta' -e GUNICORN_PORT=8000 -e GUNICORN_BIND=0.0.0.0:8000 -p 30123:8000 --name ceb-docker-prod -v /storage/data/projects/comp_support/climate_exporer_data_prep:/storage/data/projects/comp_support/climate_exporer_data_prep:ro -v /storage/data/climate/downscale/CMIP5:/storage/data/climate/downscale/CMIP5:ro docker-registry01.pcic.uvic.ca:5000/climate-explorer-backend:docker-prod
```

I *still* am not seeing good caching behaviour in the raster clipping. I know that using filename is a bit better than an attribute that may or may not exist. But the *optimal* cache key would be to use the grid properties, since those may be the same across a large set of files. For example, now when you simply change variables, the grid would be exactly the same, but it's a cache miss b/c the new variable is stored in a different file. Could you look into using grid properties as a cache key, and seeing how that performs?
