### ISSUE TITLE
Use modelmeta database version 12f290b63791 

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/climate-explorer-backend#81]
modelmeta will shortly be [enhanced](https://github.com/pacificclimate/modelmeta/pull/62) to support both gridded (existing) and discrete sampling geometry (new) data files. 

This will change the modelmeta ORM and database contents. CE backend needs to handle this.

Questions:

1. Is it possible and worth it to handle both old and new database versions? Probably looks like: 
     1. Install variant version of modelmeta in your CE backend environment
     2. In code, inspect contents of table alembic_version.
     3. In code, import and use  variant ORM classes depending on version discovered. This sounds tricky.
    4. Would this be worth the trouble?
2. If not, how do we want to handle the asynchronous changeover from old to new database version? What are the consequences (apart from the obvious) of a mismatch between database and CE backend?

**Comment by jameshiebert** [comment]
My impression of the point of database migrations (like with Alembic) is to make your database forward compatible with your application. Making the application backwards compatible with the database seems backwards to me. Doesn't seem like it would necessarily be *hard*, it just seems *wrong*. Like it adds additional complexity in the wrong place.

That said, we probably *should* ensure that the application knows which version of the database schema that it's trying to use and screams and yells if it's not compatible...

**Comment by rod-glover** [comment]
I agree that making the application backwards compatible with different database versions is adding complexity that we probably don't want. I think the better approach would be to version the application and run a compatible version against a given database.

I'm not sure that I completely understand what "make your database forward compatible with your application" means here. 

Do you mean that a migration should preserve functionality for existing application code, i.e., the old application (backend) can continuing running on the new schema? If so, the generic answer is that it can't always be done, depending on the scope and nature of the changes introduced in the migration. However, in this particular case, we could preserve compatibility by naming the ORM classes differently. 

Currently in new version, we have classes with inheritance hierarchy as follows:

```
DataFileVariable
    DataFileVariableGridded
    DataFileVariableDSGTimeSeries
```

The old version has just the class `DataFileVariable` with no subclasses.
New class  `DataFileVariableGridded` is backwards compatible with old class `DataFileVariable`

To preserve functionality, we could rename the new classes as follows:

| current name | compatibility names |
|-|-|
| `DataFileVariable` | `DataFileVariableGeneric` |
| `DataFileVariableGridded` | `DataFileVariable`, `DataFileVariableGridded` (aliases) |
| `DataFileVariableDSGTimeSeries` | _same_ |

And the renamed hierarchy looks like

```
DataFileVariableGeneric
    DataFileVariable, DataFileVariableGridded
    DataFileVariableDSGTimeSeries
```

This is probably the simplest solution for this particular issue. Wish I'd thought of it earlier.

**Comment by rod-glover** [comment]
> New class DataFileVariableGridded is backwards compatible with old class DataFileVariable

I'm pretty sure this is the case, but it needs verifying if we go this route.

**Comment by rod-glover** [comment]
I think the answer is to identify specific versions of `modelmeta` that correspond to specific stable database schemas in use, and pin to those `modelmeta` versions in specific versions of our applications (backends, indexer) that depend on them. So we would have an identified version of `modelmeta` and corresponding identified versions of applications for the current state of `pcic_meta`, and for various states of `ce_meta`.

I think implementing this should be fairly easy. In `modelmeta`, we may not have to do anything in particular, except perhaps to tag specific commits as stable versions for easy identification. In the applications, we may have to introduce some branches based on selected past commits in order to introduce whatever version pinning is necessary at a specific stage.

Does this sound like a solution? What considerations have I missed here?

**Comment by rod-glover** [comment]
You'll note that this suggestion is very different from my original suggestion, which I am not liking very much right now. I'd be very interested to hear others' evaluations of both, and any other options you may think of!

**Comment by corviday** [comment]
Hm, I don't think I entirely understand what you're proposing. Could you clarify what the structure of the relevant database tables would be?

**Comment by rod-glover** [comment]
We need to make a decision here. The following possibilities are on the table:

1. Modify the CE backend to use a database on migration 12f290b63791. The modifications are pretty simple.
2. Rename ORM classes in modelmeta to preserve existing SQLAlchemy code in CE backend. (Depending on how we feel about database table names, this may include a new migration to rename tables as well ... I'd favour that, since I really hate encountering ORM class names that conflict with database table names.)

**Comment by jameshiebert** [comment]
If using a specific migration if fairly simple, then let's go for that. (Aside: can we use named tags for migrations as well as the hash?). Then the upgrade path for CE backend becomes clear and contained. We'll have a PR that updates the migration number along with all of the  SQLAlchemy code required to run it.

Do you guys agree, @rod-glover @corviday ?

**Comment by corviday** [comment]
So, just to check my understanding, option 1 is more straightforward, while option 2 is significantly more complex but would allow us to keep  backwards compatability for modelmeta with the PDP, at least for a little while longer? Is that correct?

If so, I'd agree with going ahead with option 1. Backwards compatability is undeniably nice, but given how seldome we add new data to the PDP, it doesn't seem worth a bunch of extra work. If option 2 has _other_ benefits than backwards compatability, could @rod-glover elucidate them?

**Comment by rod-glover** [comment]
Option 2 has no benefits beyond backward compatibility, and it introduces ORM class names that are otherwise undesirable. So I say go with option 1.

And yes, we can use named tags instead of the hash. When you use alembic to create a new migration, there's a description that gets included in the migration docstring and that becomes part of its name. We could use that, or any recognizable variant of it.

**Comment by rod-glover** [comment]
This has been settled implicitly in favour of option 1 in https://github.com/pacificclimate/climate-explorer-backend/pull/154 . And I still think that is  the best choice.
