### ISSUE TITLE
Odd behaviour in make_mask_grid()

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-backend#97]
`make_mask_grid()` [generates a unique key for a combination of map grid and polygon](https://github.com/pacificclimate/climate-explorer-backend/blob/master/ce/api/geo.py#L137); it's used to determine whether a new polygon request has been previously made and doesn't need to be recalculated. The key consists of a tuple with:

- minimum longitude of the grid (float)
- maximum longitude of the grid (float)
- number of longitude steps (float)
- minimum latitude of the grid (float)
- maximum latittude of the grid (float)
- number of latitude steps (float)
- text (wkt) representation of the polygon to be computed (string)

However, during testing today, @nikola-rados was seeing singleton numpy arrays instead of numpy floats for the minimums and maximums, which is not the intended or previously observed behaviour. The obvious cause would seem to be a numpy update - numpy is not pinned in this repository - but we tried testing the steps in the python console with the newest version of numpy and they behaved as I would have expected.

This issue can be easily fixed by switching to `np.min()` instead of `np_array[0] `to determine the minimum of each coordinate, but I'd like to know _why_ it's happening and if there are any other side effects first, rather than blindly patching it. Needs further investigation.

**Comment by corviday** [comment]
This issue doesn't show up running the tests, so there's apparently something specific about the way plan2adapt is calling polygonal queries that causes it, rather than some kind of update.

**Comment by jameshiebert** [comment]
Here's sort of a minimal demonstration of this behavior, at the lowest level.

```python
$ python
Python 3.6.4 (default, Mar 20 2018, 13:12:40) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import numpy.ma
>>> a = numpy.ma.masked_array([1, 2, 3, 4, 5], mask=[True, False, False, False, False])
>>> a[0]
masked
>>> key = a[0]
>>> value = 'value'
>>> {key: value}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'MaskedConstant'
>>> key = a[1]
>>> {key: value}
{2: 'value'}
>>> numpy.min(a)
2
```

Not sure why lat/lon would be masked arrays, but maybe this gives you a lead?

**Comment by corviday** [comment]
The issues seems to be from netCDF4 version 1.5.0.1. 

[requirements.txt requires netCDF4==1.3](https://github.com/pacificclimate/climate-explorer-backend/blob/bb00d19e02b47237714a7a0441d38165867886bd/requirements.txt#L7), which works correctly, but [setup.py doesn't require any particular version of netCDF4](https://github.com/pacificclimate/climate-explorer-backend/blob/bb00d19e02b47237714a7a0441d38165867886bd/setup.py#L31), so when this package is installed as part of p2a-rules-engine's requires, it gets the most recent version of netCDF4, which, for reasons that are unclear to me but would probably make sense if I read netCDF4's CHANGELOG, renders all variables as masked arrays. 

setup.py needs to be harmonized with requirements.txt. 

I wonder if it would be possible to write a test that could automatically check whether they were in step? That seems useful.

**Comment by jameshiebert** [comment]
Good detective work! So, if I understand, this is not really an issue for this repository, only for `p2a-rules-engine`. Should we simply transfer this issue to that repo, and appropriate could simply be pegging the netCDF4 version in *its* `requirements.txt` file?

**Comment by corviday** [comment]
The issue would be fixed by pinning netCDF4 in either or both of ceb's `setup.py` or p2a's `requirements.txt`, I think. I lean toward doing it here; it feels a little cleaner and keeps the modules a little more self-contained if p2a doesn't have to manage ceb's dependencies.

**Comment by jameshiebert** [comment]
OK, a brief read of [install_requires vs. requirements.txt](https://packaging.python.org/discussions/install-requires-vs-requirements/) indicates that a case could be made for putting a general range in the `setup.py`. Particularly because we have a "known lower or upper bounds."

So I'd vote that we read the `netCDF4` CHANGELOG, figure out what the upper bound is, and add that to `setup.py`. So it might be `netCDF4<1.4` or `netCDF5<1.5`.
